server:
  port: 8081

spring:
  application:
    name: bank-front
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bank-ui
            client-secret: ui-client-secret
            authorization-grant-type: authorization_code
            scope: openid, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bank-realm
  cloud:
    consul:
      config:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  zipkin:
    tracing:
      endpoint:  http://127.0.0.1:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
  observations:
    key-values:
      rdbms:
        inline-parameters: true

logging:
  file:
    name: logs/bank.log
  level:
    root: INFO