server:
  port: 8086

spring:
  application:
    name: bank-gateway
  main:
    web-application-type: reactive
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm
  cloud:
    gateway:
      routes:
        - id: bank-accounts
          uri: http://localhost:8082
          predicates:
            - Path=/account/**
          filters:
            - name: JwtTokenRelay
        - id: bank-cash
          uri: http://localhost:8083
          predicates:
            - Path=/cash/**
          filters:
            - name: JwtTokenRelay
        - id: bank-transfer
          uri: http://localhost:8084
          predicates:
            - Path=/transfer/**
          filters:
            - name: JwtTokenRelay
    consul:
      config:
        enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    ru.yandex.practicum.gateway: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG
    reactor.netty.http.client: DEBUG
