server:
  port: 8083

spring:
  application:
    name: bank-cash
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm
      client:
        registration:
          bank-cash:
            provider: keycloak
            client-id: bank-cash
            client-secret: 0YA9hFTiIEmUSWMD4fhHYUnorIGk67BW
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/bank-realm
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

bank:
  notifications:
    base-url: http://localhost:8085

logging:
  level:
    root: INFO
    ru.yandex.practicum.cash: DEBUG
    org.springframework.security: DEBUG
    org:
      hibernate:
        SQL: DEBUG