input {
  beats {
    port => 5044
  }
}
filter {
  grok {
    match => { "message" => "%{TIME:time} %{LOGLEVEL:log_level}%{SPACE}: %{DATA:msg}, %{DATA:traceId}, %{DATA:spanId}" }
    remove_field => ["message"]
  }
  mutate {
    remove_field => [
      "username", "@timestamp", "@version", "host", "agent", "ecs",
      "input", "log", "event", "tags"
    ]
  }
}
output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "logs-%{+dd.MM.YYYY}"
    retry_on_conflict => 3
    action => "index"
    workers => 4
  }
}