server:
  port: 8085

spring:
  application:
    name: bank-notifications
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/bank-realm

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    ru.yandex.practicum.notifications: DEBUG
    org.springframework.security: DEBUG
